	/*
	 * 
	 * This program will take in a range given by the user and then test them to see if they can guess the number that has been randomly generated by the computer. 
	 * 
	 * CSC 1350 Programming project No. 6
	 * Section 2
	 * 
	 * @author Martin Dampier
	 * @since 10/21/2019
	 * 
	 */
import java.util.Scanner;
import java.lang.Math;
public class Prog06_Psychic {

	private static Scanner cin = new Scanner(System.in);
	
	/*
	 * This method is used to validate the input given to the system by the user. It checks to see if the 
	 * user has provided a variable that fits within the range they designated. 
	 * @author Martin Dampier
	 * @since 10/21/2019
	 */
	public static int inputIValidation(String errorStatement)
	{
		int rHolder = 0;			//result Holder just holds the result that meets the conditions
		boolean inputProof = false;
		
		while(!inputProof)
		{
			while(!cin.hasNextInt())
			{
				String wrong = cin.next();
				System.out.println("incorrect input");
				System.out.println("Please enter " + errorStatement);
			}
			rHolder = cin.nextInt();
			inputProof = true;
		}
		
		return rHolder;
	}
	/*
	 * This is a robust method that takes two variables given and will perform a "psychic" test to see if they user can guess a random number
	 * The method checks to see if the input is either a String or an integer to see if the user is exiting the loop. It also provides the user with a number to show how accurate they were
	 * @author Martin Dampier
	 * @since 10/21/2019
	 */
	public static void pyschicTest(int a, int b)
	{
		boolean exit = false; 		// this is a boolean to act as the exit condition to the while loop
		String sentinelCheck;		// this is a string to store any strings the user provides in the event they want to exit the program
		double countCorrect = 0;	// this stores the amount of times the user guesses the correct answer	
		double countTotal = 0;		// this stores the amount of times the user CORRECTLY attempts to GUESS. It does not store guesses outside of the bounds or faulty inputs
		
		while(!(exit))
		{
			int numToGuess = a + (int)(Math.random()*((b-a)+1)); //generates a random number in the range provided by the user a and b are placeholder values.
			System.out.println("Enter a whole number between " + a + " and " + b + " or Q to quit");
			int guess; // this will store the guess of the user (unless it isn't an integer)
			if(cin.hasNextInt())
			{
				guess = cin.nextInt();
				if(guess >= a && guess <= b)
				{
					if(guess == numToGuess)
					{
						System.out.println("Well you must be Psycic! You guessed the correct number: " + numToGuess);
						countCorrect++;
					} else
					{
						System.out.println("I am doubting your pschic abilites. You did not guess the correct number: " + numToGuess);
					}
					countTotal++;
				} else
				{
					System.out.println("You guess was out of bounds. Are you sure you are a pyschic? Let's try again");
				}
			} else
			{
				sentinelCheck = cin.next();
				if(sentinelCheck.equals("Q"))
				{
					exit = true;	
				} else
				{
					System.out.println("Not the sentinel value or an integer");
				}
			}
		}
		double successRate = (countCorrect/countTotal)*100;				// this variable is to calculate and pass the percent correct to the printf statement
		System.out.printf("Your success rate is %4.2f%%", successRate);
	}
	/*
	 * This is the main method and it prompts the user to get the upper and lower bounds of the range they will use in the psychic test. It utilizes
	 * input validation to ensure the user is inputing integers for the range. 
	 * @author Martin Dampier
	 * @since 10/21/2019
	 */
	public static void main(String[] args) 
	{
		int start = 0;
		int end = 0;
		int rangeCheck;
		boolean isGreaterThanThree = false;
		
		String lowerPromptError = "Enter a integer value";
		
		System.out.println("So you think you're psychic? Well, let's put that to the test!");
		System.out.println("I will pick a number in a range, abd you have to \"guess\" what the number is.");
		System.out.println("I will let you pick the range");
		System.out.println("Enter the lower bound of the range: ");
		start = inputIValidation(lowerPromptError);
		rangeCheck = start + 3;
		System.out.println("Enter the upper bound of the range (at least 3 numbers higher than " + start + "): ");
		String upperPromptError = "Enter a integer value";
		end = inputIValidation(upperPromptError);
		while(!isGreaterThanThree)
		{
			if (!(end >= rangeCheck))
			{
				System.out.println("Your upper value did not fufill the requirements.");
				System.out.println("Please enter another value");
				end = inputIValidation(upperPromptError);
			} else
			{
				isGreaterThanThree = true;
			}
		}
		pyschicTest(start, end);
	}

}
